### ISSUE TITLE
Opportunistic Scanning

### ISSUE THREAD

**Issue by mike-audi** [tiki/capture#2]
### Description

The goal is to provide a simplified developer experience that opportunistically scans users linked accounts, going back years, without duplicates, and without creating long running tasks that will get killed. 

### Issues

- [x] #11
- [ ] tiki/publish-client-android/issues/88
- [ ] tiki/publish-client-android/issues/89
- [ ] tiki/publish-client-ios/issues/79
- [ ] tiki/publish-client-ios/issues/80
