### ISSUE TITLE
Capture Receipt SDK

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture#4]
### Description

The Capture Receipt is currently used as a library that enables the App Receipt to capture data from scanning physical receipts, scraping email accounts, and connecting online retailer accounts.

Now we want to transform this library into a standalone product that makes it possible not only for the capturing of the data but its licensing and publishing. It will simplify our internal usage, move the business logic out of the apps layer, and will allow other organizations to use it with their users.

### Android
- [x] tiki/capture-receipt-android/issues/1
- [x] tiki/capture-receipt-android/issues/2
- [x] tiki/capture-receipt-android/issues/3
- [x] tiki/capture-receipt-android/issues/4
- [x] tiki/capture-receipt-android/issues/5
- [x] tiki/capture-receipt-android/issues/6
- [x] tiki/capture-receipt-android/issues/7
- [x] tiki/capture-receipt-android/issues/8

### iOS
- [x] tiki/capture-receipt-ios/issues/2
- [x] tiki/capture-receipt-ios/issues/3
- [x] tiki/capture-receipt-ios/issues/4
- [x] tiki/capture-receipt-ios/issues/5
- [x] tiki/capture-receipt-ios/issues/6
- [x] tiki/capture-receipt-ios/issues/7
- [x] tiki/capture-receipt-ios/issues/8
- [x] tiki/capture-receipt-ios/issues/9
- [x] tiki/capture-receipt-ios/issues/16
