### ISSUE TITLE
Android - Update the capture APIs for email and physical receipts

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture#7]
### Description

Update the capture receipt library to integrate with the new API infrastructure as described in tiki/apps#59 and tiki/apps#65.

### Issues

- [x] tiki/capture-receipt-android#18
- [x] tiki/capture-receipt-android#19
- [x] tiki/capture-receipt-android#20
- [x] tiki/capture-receipt-android#21
- [x] tiki/capture-receipt-android#22
- [x] tiki/capture-receipt-android#25
- [x] tiki/capture-receipt-android#26
- [x] tiki/capture-receipt-android#27
- [x] tiki/capture-receipt-android#28
- [x] tiki/capture-receipt-android#29
- [x] tiki/capture-receipt-android#30
