### ISSUE TITLE
iOS - Update the capture APIs for email and physical receipts

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture#8]
### Description

Update the capture receipt library to integrate with the new API infrastructure as described in tiki/apps#59 and tiki/apps#65.

### Issues

- [x] tiki/capture-receipt-ios/issues/25
- [x] tiki/capture-receipt-ios/issues/26
- [x] tiki/capture-receipt-ios/issues/27
- [x] tiki/capture-receipt-ios/issues/29
- [x] tiki/capture-receipt-ios/issues/30
- [x] tiki/capture-receipt-ios/issues/31
- [x] tiki/capture-receipt-ios/issues/32
- [x] tiki/capture-receipt-ios/issues/33
- [x] tiki/capture-receipt-ios/issues/34
- [x] tiki/capture-receipt-ios/issues/35
- [x] tiki/capture-receipt-ios/issues/36
