### ISSUE TITLE
Capacitor - Update the capture APIs for email and physical receipts

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture#9]
### Description

Update the capture receipt library to integrate with the new API infrastructure as described in tiki/apps#59 and tiki/apps#65.

### Issues

- [x] tiki/capture-receipt-capacitor/issues/485
- [x] tiki/capture-receipt-capacitor/issues/486
- [x] tiki/capture-receipt-capacitor/issues/487
- [x] tiki/capture-receipt-capacitor/issues/488
- [x] tiki/capture-receipt-capacitor/issues/489
- [ ] tiki/capture-receipt-capacitor/issues/497
- [ ] tiki/capture-receipt-capacitor/issues/498
- [ ] tiki/capture-receipt-capacitor/issues/499
- [ ] tiki/capture-receipt-capacitor/issues/500
- [ ] tiki/capture-receipt-capacitor/issues/501
- [ ] tiki/capture-receipt-capacitor/issues/502
- [ ]  tiki/capture-receipt-capacitor/issues/504

**Comment by ricardobrg** [comment]
Closing as outdated. A new milestone needs to be created to implement the client library in capacitor
